# PHP
# Test and package your PHP application.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

pool:
  vmImage: 'Ubuntu 16.04'

steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(system.defaultWorkingDirectory)'
        includeRootFolder: false
    - task: PublishBuildArtifacts@1